// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as ModelService from "./modelservice.js";
export {
    ModelService
};

export type {
    ASRResult,
    ModelInfo,
    RuntimeInfo
} from "./models.js";
