// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface ASRResult {
    "text": string;
    "language"?: string;
}

/**
 * GenerationProgressInfo 生成进度快照（轮询用，跨过事件链路）。
 */
export interface GenerationProgressInfo {
    "available": boolean;
    "percent": number;
    "phase": string;
    "step": number;
    "total": number;
    "message": string;
}

/**
 * ImageOutput 产物历史条目（磁盘 outputs 目录持久化，png + meta + 缩略图）。
 */
export interface ImageOutput {
    "id": string;
    "model": string;
    "prompt": string;
    "width": number;
    "height": number;
    "steps": number;
    "cfgScale": number;
    "seed": number;

    /**
     * unix 毫秒
     */
    "createdAt": number;

    /**
     * base64 JPEG 缩略图
     */
    "thumb": string;
}

export interface ImageOutputDetail {
    /**
     * base64 PNG
     */
    "image": string;
    "output": ImageOutput;
}

/**
 * ModelInfo 模型展示信息（与前端绑定契约一致）。
 */
export interface ModelInfo {
    "name": string;
    "displayName": string;
    "type": string;
    "description": string;
    "capabilities": string[] | null;
    "tags": string[] | null;
    "runtimes": string[] | null;
    "version": string;
    "installed": boolean;
    "status": string;
    "vendor": string;
    "engine": string;
    "parameters"?: { [_ in string]?: any } | null;
}

/**
 * RuntimeInfo 运行时展示信息（与前端绑定契约一致）。
 */
export interface RuntimeInfo {
    "name": string;
    "displayName": string;
    "description": string;
    "version": string;
    "installed": boolean;
    "status": string;
    "vendor": string;
    "backend": string;
}
