// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface ASRResult {
    "text": string;
    "language"?: string;
}

/**
 * ModelInfo 模型展示信息（与前端绑定契约一致）。
 */
export interface ModelInfo {
    "name": string;
    "displayName": string;
    "type": string;
    "description": string;
    "capabilities": string[] | null;
    "tags": string[] | null;
    "runtimes": string[] | null;
    "version": string;
    "installed": boolean;
    "status": string;
    "vendor": string;
    "engine": string;
}

/**
 * RuntimeInfo 运行时展示信息（与前端绑定契约一致）。
 */
export interface RuntimeInfo {
    "name": string;
    "displayName": string;
    "description": string;
    "version": string;
    "installed": boolean;
    "status": string;
    "vendor": string;
    "backend": string;
}
