// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ModelService Wails 绑定门面。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CancelInstallModel 取消进行中的模型安装。
 */
export function CancelInstallModel(name: string): $CancellablePromise<void> {
    return $Call.ByID(2404362283, name);
}

/**
 * Close 停止全部模型并关闭 supervisor（幂等）。
 */
export function Close(): $CancellablePromise<void> {
    return $Call.ByID(2541203879);
}

/**
 * DeleteImageOutput 删除一条产物。
 */
export function DeleteImageOutput(id: string): $CancellablePromise<void> {
    return $Call.ByID(4202774494, id);
}

/**
 * GenerateImage sd.cpp 文生图（/sdapi/v1/txt2img），成功后把产物存档到 outputs。
 */
export function GenerateImage(request: string): $CancellablePromise<string> {
    return $Call.ByID(968649563, request);
}

/**
 * GenerationProgress 查询某模型当前生成进度（由 sd-server stdout 解析而来）。
 */
export function GenerationProgress(model: string): $CancellablePromise<$models.GenerationProgressInfo> {
    return $Call.ByID(729071116, model);
}

/**
 * GetImageOutput 取单个产物完整图 + 元信息。
 */
export function GetImageOutput(id: string): $CancellablePromise<$models.ImageOutputDetail> {
    return $Call.ByID(448576701, id);
}

/**
 * GetModel 取单个模型。
 */
export function GetModel(name: string): $CancellablePromise<$models.ModelInfo> {
    return $Call.ByID(3269108072, name);
}

/**
 * GetRuntime 取单个运行时。
 */
export function GetRuntime(name: string): $CancellablePromise<$models.RuntimeInfo> {
    return $Call.ByID(4094558573, name);
}

/**
 * InstallModel 安装模型（阻塞、可经 CancelInstallModel 取消）。
 */
export function InstallModel(name: string): $CancellablePromise<void> {
    return $Call.ByID(3584340153, name);
}

/**
 * InstallRuntime 安装运行时（阻塞式 Wails 调用；进度经 mc:install 事件推送）。
 */
export function InstallRuntime(name: string): $CancellablePromise<void> {
    return $Call.ByID(1821675968, name);
}

/**
 * ListImageOutputs 列出全部产物（新→旧）。
 */
export function ListImageOutputs(): $CancellablePromise<$models.ImageOutput[] | null> {
    return $Call.ByID(2378784664);
}

/**
 * ListModels 列出模型（catalog 展示信息 + manager 安装/运行状态）。
 */
export function ListModels(filter: string): $CancellablePromise<$models.ModelInfo[] | null> {
    return $Call.ByID(2732245531, filter);
}

/**
 * ListRuntimes 列出运行时。
 */
export function ListRuntimes(): $CancellablePromise<$models.RuntimeInfo[] | null> {
    return $Call.ByID(4107377592);
}

/**
 * ParseRequest 解析前端传入的 JSON 请求字符串。
 */
export function ParseRequest(request: string, out: any): $CancellablePromise<void> {
    return $Call.ByID(3767228705, request, out);
}

/**
 * StartModel 启动模型（自动前置安装引擎、复用已运行实例）。
 */
export function StartModel(name: string): $CancellablePromise<void> {
    return $Call.ByID(433848808, name);
}

/**
 * StopModel 停止模型。
 */
export function StopModel(name: string): $CancellablePromise<void> {
    return $Call.ByID(1861099118, name);
}

/**
 * Synthesize audio.cpp 语音合成（/v1/audio/speech）。
 */
export function Synthesize(request: string): $CancellablePromise<string> {
    return $Call.ByID(1911687313, request);
}

/**
 * Transcribe audio.cpp 离线语音识别（/v1/audio/transcriptions）。
 */
export function Transcribe(request: string): $CancellablePromise<$models.ASRResult> {
    return $Call.ByID(3520956434, request);
}

/**
 * UninstallModel 卸载模型。
 */
export function UninstallModel(name: string): $CancellablePromise<void> {
    return $Call.ByID(3795133770, name);
}

/**
 * UninstallRuntime 卸载运行时（先停其名下所有模型进程）。
 */
export function UninstallRuntime(name: string): $CancellablePromise<void> {
    return $Call.ByID(3988057147, name);
}
